GPII/universal

package.json
=> KETTLE-25: Updated reference to latest kettle, now supporting CORS for POST and PUT

gpii/node_modules/gpii-oauth2/gpii-oauth2-authz-server/public/src/components/privacySettings/js/EditPrivacySettings.js
See http://issues.gpii.net/browse/GPII-1124
=> GPII-1124: Move EditPrivacySettings setDoneState to the model 

testData/preferences/c4a_p3_katia.json, testData/preferences/c4a_p3_maria.json
Maria also needed to have EasyOne on Windows; Katia needed volume settings on Android.
=> GPII-1126: Changes in maria and katia

testData/deviceReporter/installedSolutions_supernova.json, testData/deviceReporter/linux_installedSolutions.json, testData/deviceReporter/osx_installedSolutions.json, testData/deviceReporter/win32_installedSolutions.json
This pull request removes a bunch of solutions from the device reporter
files because these solutions are incompatible with the platforms they
were listed for. In addition, screen resolution was added for Windows.
=> GPII-1142: incompatible solutions in dev reporter

testData/preferences/c4a_p3_maria.json, testData/preferences/c4a_p3_maria_de.json, testData/preferences/c4a_p3_maria_el.json, testData/preferences/c4a_p3_maria_es.json, testData/preferences/c4a_p3_michael.json
Michael: font face Arial added to RW Gold settings for consistency with
Cloud4Chrome.
Maria: No SuperNova settings; Java ME settings added; non-English
versions of the NP set added; Easy123 removed from non-English NP sets.
=> GPII-1126: updates to Maria's and Michael's NP sets

testData/preferences/acceptanceTests/screenreader_nvda.json, testData/solutions/win32.json, tests/platform/android/android-talkback-testSpec.js, tests/platform/linux/linux-orca-testSpec.js, tests/platform/windows/windows-nvda-testSpec.js
As required to support the latest version of NVDA
=> GPII-1138: Wrapped the NVDA transformer in a round and updated tests

testData/preferences/c4a_p3_michael.json
Replace the horrible Arial fontface with Verdana and increase the line height in Michael's NP set (use case 7), as requested by Ivan (27 May 2015).
=> GPII-1126: Verdana in Michael's NP set

testData/preferences/chris.md, testData/preferences/franklin.md, testData/preferences/li.md, testData/preferences/manuel.md, testData/preferences/mary.md, testData/preferences/vladimir.md
My fault; should get a better grip on GitHub's Markdown dialect ;-)
=> GPII-966 / NOJIRA: sublists with spaces; typos

documentation/OldPreferencesServer.md, documentation/PreferencesServer.md, gpii/node_modules/matchMakerFramework/test/js/MatchMakerUtilitiesTests.js, gpii/node_modules/preferencesServer/test/data/np_flatOnly_singleContext.json, gpii/node_modules/preferencesServer/test/data/np_mixed_singleContext.json, gpii/node_modules/preferencesServer/test/data/np_tiny.json, gpii/node_modules/preferencesServer/test/preferencesServerTests.js, gpii/node_modules/rawPreferencesServer/test/RawPreferencesTest.js, testData/ontologies/ISO24751-flat.json, testData/preferences/MikelVargas.json, testData/preferences/acceptanceTests/fm_gnome_keyboard.json, testData/preferences/manuel.json, testData/preferences/mary.json
mary: The right common term according to our ontology is onscreenKeyboard
manuel: Missing the "flat" wrapper
=> NOJIRA: Fixed some NP sets for the integration weekly tests

gpii/node_modules/flowManager/src/BrowserChannel.js, gpii/node_modules/flowManager/src/FlowManager.js, gpii/node_modules/flowManager/test/BrowserChannelTests.js, gpii/node_modules/flowManager/test/data/browserChannel_solutionsRegistry.json, gpii/node_modules/lifecycleManager/src/LifecycleManager.js, gpii/node_modules/lifecycleManager/test/html/LifecycleManagerTest.html, gpii/node_modules/settingsHandlers/src/WebSocketsComponent.js, gpii/node_modules/settingsHandlers/test/WebSocketsSettingsHandlerTests.js, gpii/node_modules/testing/src/Integration.js, testData/solutions/linux.json, tests/platform/linux/linux-chrome-testSpec.js
renaming WebSockets to webSockets for settings handler name - reindenting files that now no longer require wrapping - @kaspermarkus
=> GPII-1232: Moving WebSockets component up to flowManager.io -

testData/preferences/review4/Alicia.json, testData/preferences/review4/README.md
NP set for Alicia and readme file explaining the purposes of these NP sets
=> GPII-1149: NP set for Alicia, C4A review 4

README.md, package.json
This refers to https://github.com/fluid-project/dedupe-infusion/pull/1 - this package.json will need to be updated once that is merged
=> GPII-1259: Moved to use of dedupe-infusion micromodule rather than grunt task

testData/preferences/review4/Bob.json
@AndreasStiegler, can you check whether anything else is needed in this pull request?
=> GPII-1194: NP set for Bob (review4)

gpii/node_modules/deviceReporter/src/DeviceReporter.js, testData/preferences/acceptanceTests/readwritegold_application1.json, testData/solutions/win32.json, tests/platform/index-windows.js, tests/platform/windows/configs/windows-dynamicDeviceReporter-config.json, tests/platform/windows/configs/windows-dynamicDeviceReporter-config.txt, tests/platform/windows/windows-dynamicDeviceReporter-testSpec.js, tests/platform/windows/windows-dynamicDeviceReporter-testSpec.txt
https://issues.gpii.net/browse/GPII-776
This pull may need some small adjustments based on Javi's work.
=> Gpii 776 windows device reporter

testData/preferences/alice.json, testData/preferences/alice.md, testData/preferences/davey.json, testData/preferences/davey.md, testData/preferences/david.json, testData/preferences/david.md, testData/preferences/elaine.md, testData/preferences/elod.json, testData/preferences/elod.md, testData/preferences/livia.json, testData/preferences/livia.md
https://issues.gpii.net/browse/GPII-1502
=> GPII-1502 Adding profiles from LGS and other demos with user stories.

gpii/node_modules/deviceReporter/src/DeviceReporter.js, gpii/node_modules/deviceReporter/src/DeviceReporterUtilities.js, gpii/node_modules/testing/src/Integration.js, tests/platform/windows/windows-dynamicDeviceReporter-testSpec.js
=> GPII-776: Fixed the dynamic device reporter windows test to also be runnable as integration tests

gpii/configs/review4.scenario3.production.json, gpii/node_modules/flowManager/configs/development.json, gpii/node_modules/flowManager/src/FlowManager.js, gpii/node_modules/lifecycleManager/src/LifecycleManager.js, gpii/node_modules/matchMakerFramework/src/MatchMakerCapabilities.json, gpii/node_modules/matchMakerFramework/src/MatchMakerFramework.js, testData/preferences/review4/Bob.json
hey @javihernandez - I've tested this code to the extend currently possible, and it mostly seem to be working. There still seems to be a minor issue with the dispatcher prioritizing the flat matchmaker over the statistical ones, and when testing it I had problems with the statistical matchmakers. @AndreasStiegler is looking into this, and once he green lights it, I think it should be ready to merge.
Anyway, I made the pull request in case you wanted to give it a sanity check and see if there is something obvious that I should change ... We will let you know when it's ready to be tested and merged
=> GPII-1197: Try different functionality

gpii/node_modules/lifecycleManager/src/LifecycleManager.js, gpii/node_modules/lifecycleManager/test/js/LifecycleManagerTests.js, gpii/node_modules/settingsHandlers/src/settingsHandlerUtilities.js, gpii/node_modules/settingsHandlers/test/web/js/SettingsHandlerUtilitiesTests.js
GPII-1518: Fixed the issue so state is now properly restored, even onmodifications of settings/apps that weren't originally modified on login. Tests are included as well
=> GPII-1518: Fixed the issue so state is now properly restored

gpii/configs/review4.scenario3.production.json, gpii/node_modules/flowManager/configs/development.json, gpii/node_modules/lifecycleManager/src/LifecycleManager.js, gpii/node_modules/lifecycleManager/test/js/LifecycleManagerTests.js, gpii/node_modules/matchMakerFramework/src/MatchMakerCapabilities.json, testData/preferences/review4/Bob.json
Also fixed web-based tests, as they were broke in the review4 branch
=> GPII-1518: Fix to state not being properly stored on updates.

testData/preferences/olb_preferences.md
This change was previously part of another pull request: https://github.com/GPII/universal/pull/433.
=> NOJIRA: Markdown markup for list items fixed.

Vagrantfile
To test, retrieve this PR and run:
```
vagrant up
grunt tests
```
=> GPII-1855 - Upgrade to Fedora 24

gpii/configs/gpii.config.all.development.dr.production.txt, gpii/configs/gpii.config.cloudBased.development.all.local.txt, gpii/configs/gpii.config.development.all.local.txt, gpii/configs/gpii.config.untrusted.development.all.local.txt
Also updated the titles of the rest of the .txt files to fit the filename
=> GPII-1979: Updated the documentation on the port.

testData/deviceReporter/acceptanceTests/readWrite.json, testData/preferences/acceptanceTests/rwg1.json, testData/preferences/acceptanceTests/rwg2.json, testData/solutions/solutionsDescription/com_texthelp_readWriteGold.md, testData/solutions/win32.json, tests/platform/index-windows.js, tests/platform/windows/configs/gpii.tests.acceptance.windows.readWrite.config.json, tests/platform/windows/configs/gpii.tests.acceptance.windows.readWrite.config.txt, tests/platform/windows/windows-dynamicDeviceReporter-testSpec.js, tests/platform/windows/windows-readWrite-testSpec.js, tests/platform/windows/windows-readWrite-testSpec.txt
https://issues.gpii.net/browse/GPII-1999
* Updated  to RWG11
* Fixed the "isInstalled" block in the solutions registry
* Added acceptance tests
* Added solutions description file
* Fixed dynamic device reporter tests for RWG
=> GPII-1999 Updating RWG Solution for RWG11

package.json
More info at https://issues.gpii.net/browse/GPII-2483
=> GPII-2483: Updated kettle ref

gpii/node_modules/lifecycleManager/src/LifecycleManager.js, gpii/node_modules/settingsHandlers/src/settingsHandlerUtilities.js, gpii/node_modules/testing/src/Integration.js, gpii/node_modules/testing/src/Testing.js, tests/IntegrationTests.js, tests/JournalIntegrationTests.js
@javihernandez - if you replace the gpii-app's reference to universal with this one, the two races we saw should be fixed
=> GPII-2522: Fixes exposed by race conditions in gpii-app tests

documentation/RawPreferencesServer.md, documentation/SolutionsRegistryFormat.md, documentation/Transformer.md
These commits fix some obvious editorial changes such as missing spaces in markdown and a few typos.
=> NOJIRA: minor editorial changes

gpii/node_modules/eventLog/index.js, gpii/node_modules/eventLog/src/eventLog.js, gpii/node_modules/eventLog/src/metrics.js, gpii/node_modules/eventLog/test/EventLogTests.js
Works well with https://github.com/GPII/windows/pull/150
=> GPII-2583: Metrics improvements

testData/solutions/linux.json5, testData/solutions/win32.json5, tests/platform/shared/uioPlusTestDefs.js
https://issues.gpii.net/browse/GPII-2612
=> GPII-2612: Correcting ToC transformation for uio+ solution

gpii/node_modules/flowManager/test/PCPChannelTests.js, testData/preferences/uioPlusCommon.md, testData/preferences/uioPlus_character_space.md, testData/preferences/uioPlus_defaults.md, testData/preferences/uioPlus_font_size.md, testData/preferences/uioPlus_high_contrast.md, testData/preferences/uioPlus_highlight_colour.md, testData/preferences/uioPlus_inputs_larger.md, testData/preferences/uioPlus_line_space.md, testData/preferences/uioPlus_multiple_settings.md, testData/preferences/uioPlus_multiple_support_tool.md, testData/preferences/uioPlus_self_voicing.md, testData/preferences/uioPlus_simplified.md, testData/preferences/uioPlus_support_tool.md, testData/preferences/uioPlus_syllabification.md, testData/preferences/uioPlus_toc.md, testData/preferences/uioPlus_unhandled_support_tool.md, testData/solutions/linux.json5, testData/solutions/solutionsDescription/net_gpii_uioPlus.md, testData/solutions/win32.json5, tests/platform/linux/configs/gpii.tests.acceptance.linux.uioPlus.config.txt, tests/platform/linux/linux-uioPlus-testSpec.txt, tests/platform/shared/uioPlusTestDefs.js, tests/platform/windows/configs/gpii.tests.acceptance.windows.uioPlus.config.txt, tests/platform/windows/windows-uioPlus-testSpec.txt
https://issues.gpii.net/browse/GPII-2740
=> GPII-2740: Renamed UIO+ Browser Extention to just UIO+

gpii/node_modules/flowManager/src/FlowManagerRequests.js, gpii/node_modules/flowManager/src/UserLogonStateChange.js, tests/UntrustedUserLogonStateChangeTests.js, tests/shared/UserLogonStateChangeTestDefs.js
Added error handling for failed login with proximity trigge (clearing state) and a test for it
=> GPII-2562, GPII-2768: Added error handling for failed login with proximity trigger, etc

README.md
See [GPII-2903](https://issues.gpii.net/browse/GPII-2903) for details.
=> GPII-2903: Update location of coverage report in documentation.

testData/solutions/win32.json5, tests/JournalIntegrationTests.js, tests/platform/windows/windows-builtIn-testSpec.js
All credit to @klown for actually doing the changes
=> GPII-1230: update of the registered at query funciton according to josephs review

testData/ontologies/flat.json5, testData/ontologies/mappings/ISO24751-flat.json5, testData/preferences/uioPlusCommon.json5, testData/preferences/uioPlus_captions.json5, testData/preferences/uioPlus_character_space.json5, testData/preferences/uioPlus_defaults.json5, testData/preferences/uioPlus_font_size.json5, testData/preferences/uioPlus_high_contrast.json5, testData/preferences/uioPlus_highlight_colour.json5, testData/preferences/uioPlus_inputs_larger.json5, testData/preferences/uioPlus_line_space.json5, testData/preferences/uioPlus_multiple_settings.json5, testData/preferences/uioPlus_self_voicing.json5, testData/preferences/uioPlus_simplified.json5, testData/preferences/uioPlus_support_tool.json5, testData/preferences/uioPlus_syllabification.json5, testData/preferences/uioPlus_toc.json5, testData/preferences/uioPlus_unhandled_support_tool.json5, testData/solutions/linux.json5, testData/solutions/win32.json5, tests/platform/linux/linux-uioPlus-testSpec.txt, tests/platform/shared/uioPlusTestDefs.js, tests/platform/windows/windows-uioPlus-testSpec.txt
https://issues.gpii.net/browse/GPII-3154
https://issues.gpii.net/browse/GPII-3156
Need to update UIO+ to support these features.
=> GPII-3154, GPII-3156: Onboarding for Captions and Low Contrast for UIO+

gpii/node_modules/gpii-ini-file/index.js, gpii/node_modules/gpii-ini-file/test/iniFileTests.js
For the Jaws solution crashing.
=> NOJIRA: Stopped crashing when writing a new ini file.

gpii/node_modules/flowManager/test/PSPChannelTests.js, testData/ontologies/flat.json5, testData/solutions/win32.json5
Also, it includes the tiny fix for the gray/grey inconsistency of UIO+ (GPII-3383)
=> GPII-3382: Added new high contrast themes

testData/solutions/win32.json5
See https://issues.gpii.net/browse/GPII-3401
=> GPII-3401: Disabled Maavis

gpii/node_modules/matchMakerFramework/test/inverseCapabilities/jaws_application_expected.json, testData/deviceReporter/installedSolutions.json, testData/solutions/win32.json5, tests/data/preferences/jaws_common.json5, tests/data/preferences/jaws_common2.json5, tests/data/preferences/jaws_common3.json5
This pull request has been tested with QSS1.1 to make sure it does solve the issue 2 stated in [GPII-3400](https://issues.gpii.net/browse/GPII-3400).
=> GPII-3400: Modify the solution registry for matching "volume" preference

gpii/node_modules/flowManager/test/PSPChannelTests.js, testData/preferences/snapset_2a.json5, testData/preferences/snapset_2b.json5, testData/preferences/snapset_2c.json5, testData/preferences/snapset_4d.json5
See https://issues.gpii.net/browse/GPII-3415
=> GPII-3415: Removed highContrast application-specific terms from snapsets

gpii/node_modules/eventLog/src/eventLog.js, gpii/node_modules/eventLog/src/metrics.js, gpii/node_modules/eventLog/test/EventLogTests.js
A filename was generated by the current time - which contains colons, `:`.
(it passes CI because colons have no special meaning Linux filesystems)
=> NOJIRA: Removed colon from filename.

testData/solutions/win32.json5
See https://github.com/GPII/windows/pull/217
=> GPII-2618: Restoring wallpaper after high contrast.

gpii/node_modules/gpii-ini-file/index.js, gpii/node_modules/gpii-ini-file/test/iniFileTests.js, gpii/node_modules/gpii-ini-file/test/read-test.ini, gpii/node_modules/gpii-ini-file/test/write-test.expect.ini, gpii/node_modules/gpii-ini-file/test/write-test.ini
Fixes an issue where settings couldn't be added to the final group in the ini file.
=> GPII-3684: Inifile last section

gpii/node_modules/lifecycleManager/src/UserLogonRequest.js, gpii/node_modules/matchMakerFramework/src/MatchMakerUtilities.js, gpii/node_modules/matchMakerFramework/test/js/MatchMakerUtilitiesTests.js, gpii/node_modules/transformer/index.js, gpii/node_modules/transformer/src/js/Transformer.js, gpii/node_modules/transformer/test/html/TransformerTests.html, gpii/node_modules/transformer/test/js/TransformerTests.js, testData/solutions/win32.json5, tests/JournalIntegrationTests.js
@amb26, @javihernandez, this pull request also changes the windows solution registry "win32.json5" to sync up [the format of "update" array elements](https://github.com/cindyli/universal/commit/239c212a95ddcee744137757b2fec905739711a6#diff-cb7e20a6c5ff97630ea4518024a845b2R6964) that now all have "settings." prefix.
=> GPII-3653: Transformer only dispatch settings handlers that support at least one of the requested preferences

README.md, testData/solutions/win32.json5
See https://issues.gpii.net/browse/GPII-3761
=> GPII-3761: Restored com.microsoft.windows.highContrast isInstalled block

gpii/configs/gpii.config.cloudBased.development.manualTesting.json5, gpii/configs/gpii.config.development.manualTesting.json5, gpii/configs/gpii.config.preferencesServer.standalone.development.manualTesting.json5, gpii/configs/gpii.config.untrusted.development.dynamicDR.manualTesting.json5, gpii/configs/gpii.config.untrusted.development.manualTesting.json5, gpii/configs/shared/gpii.config.couch.development.base.json5, gpii/configs/shared/gpii.config.couch.development.startWithCleanData.json5, gpii/configs/shared/gpii.config.couch.development.startWithoutCleanData.json5
See [GPII-3779](https://issues.gpii.net/browse/GPII-3779) for details.
=> GPII-3779: Add a "start clean" couchdb config.

gpii/configs/gpii.config.untrusted.production.dynamicDR.json5, gpii/configs/gpii.config.untrusted.production.dynamicDR.manualTesting.json5
=> GPII-3744: Updated documentation of the production configurations

testData/solutions/win32.json5
Required SR change for https://github.com/GPII/windows/pull/254
=> GPII-3811: Make custom high-contrast themes work with updated Windows.

testData/solutions/win32.json5
Re-issued closed pull request with latest feedback.
=> GPII-3652: Onboard new version of Read&Write

gpii/node_modules/flowManager/src/ReadyGetHandler.js, gpii/node_modules/flowManager/src/SettingsGetHandler.js, gpii/node_modules/flowManager/src/SettingsPutHandler.js, gpii/node_modules/flowManager/src/UserLogonHandlers.js, gpii/node_modules/preferencesServer/src/preferencesGetHandler.js, gpii/node_modules/preferencesServer/src/preferencesPutHandler.js, gpii/node_modules/solutionsRegistry/src/schemas/solution-schema.json5, gpii/node_modules/solutionsRegistry/test/GenericTermsTests.js, gpii/node_modules/solutionsRegistry/test/SettingsPayloadTests.js, gpii/node_modules/solutionsRegistry/test/SolutionsRegistryFileTests.js, gpii/node_modules/solutionsRegistry/test/lib/validation.js, package.json, testData/solutions/win32.json5
See [GPII-3972](https://issues.gpii.net/browse/GPII-3972) for details.
cc: @amb26
=> GPII-3972: Address performance issues with validated endpoints.

testData/deviceReporter/installedSolutions.json, testData/preferences/otis.json5, testData/solutions/solutionsDescription/com_microsoft_office.md, testData/solutions/win32.json5
Here's the onboarding of the ribbon, toolbar, and status bars for these Office applications:
* Word
* Excel
* PowerPoint
* Publisher
* OneNote
* Access
* Outlook
More info in https://docs.google.com/document/d/1uSThshbBb1bEz6oYdRRHKfqpTNkNfjqYi0ouUbXCTeY/edit#
Testing: Requires Office 2016, the user `otis` performs various customisations of each Office application.
=> GPII-3448: Office on-boarding

gpii/node_modules/userListeners/src/usb.js, gpii/node_modules/userListeners/test/usbTests.js
Fixes https://issues.gpii.net/browse/GPII-3978.
Full specs are here described in https://issues.gpii.net/browse/GPII-2682
=> GPII-3978: The latest USB added takes precedence over any prior USB keys

testData/defaultSettings/defaultSettings.win32.json5
See https://issues.gpii.net/browse/GPII-4017
=> GPII-4017: Added office simplification to reset to standard profile

gpii/node_modules/userListeners/src/listeners.js
See https://github.com/GPII/universal/pull/795#issuecomment-508556055
Related windows code: https://github.com/GPII/windows/pull/155/commits/a5e61e9aad6dca57b7f7f0634e5b231829daaab5#diff-740552bcf8bd9d31886138b241b1ffb6R31
(this PR does not depend on the GPII-2338 service PR, https://github.com/GPII/windows/pull/155/)
=> GPII-3988: Added support for environmental logins in the user listeners.

scripts/migration/migration-GPII-3711.js, testData/defaultSettings/defaultSettings.win32.json5, tests/data/dbData/clientCredentials.json, tests/shared/FlowManagerSettingsPutTestDefs.js
To supplement the change made thru https://github.com/GPII/universal/pull/800
=> GPII-4017: Adjust tests and the NOVA migration script for adding office simplification

scripts/generateCredentials.js
See https://issues.gpii.net/browse/GPII-4021
=> GPII-4021: Updated generateCredentials script to match 0.2 schema

gpii/node_modules/flowManager/src/FlowManager.js, gpii/node_modules/lifecycleManager/src/LifecycleManager.js, gpii/node_modules/lifecycleManager/src/LifecycleManagerSession.js
This pull request fixes the first 2 issues described in [GPII-4012](https://issues.gpii.net/browse/GPII-4012).
=> GPII-4012: Fix some anomalous names and structures in Flow Manager and Lifecycle Manager

gpii/node_modules/solutionsRegistry/test/SettingsPayloadTests.js
See [https://issues.gpii.net/browse/GPII-4303](https://issues.gpii.net/browse/GPII-4303) for details.
cc: @amb26
=> GPII-4303: Adjust test timing and log the observed times.

gpii/node_modules/solutionsRegistry/src/js/sr-validation-middleware.js, gpii/node_modules/solutionsRegistry/test/ValidationMiddlewareTests.js, testData/preferences/intra_application.json5
See [GPII-4323](https://issues.gpii.net/browse/GPII-4323) for details.
cc: @amb26 @JavierJF
=> GPII-4323: Transform payloads before validation.

gpii/node_modules/solutionsRegistry/test/SettingsPayloadTests.js, gpii/node_modules/solutionsRegistry/test/SolutionsRegistryFileTests.js, testData/preferences/intra_application.json5, testData/preferences/tony.json5, testData/solutions/win32.json5
Fixes mouse settings and other recent bugs related to validating intra-application settings.  See [GPII-4344](https://issues.gpii.net/browse/GPII-4344) for details.
cc: @amb26
=> GPII-4344: Tested all capabilities transformations and fixed errors.

gpii/node_modules/solutionsRegistry/test/SolutionsRegistryFileTests.js, testData/preferences/GPII-270-rbmm-demo.json5, testData/preferences/intra_application.json5, testData/preferences/simon.json5, testData/solutions/win32.json5
See [GPII-4372](https://issues.gpii.net/browse/GPII-4372) for details.
cc: @amb26 @sgithens
=> GPII-4372: Add additional checks for windows settings handlers that work with object values.

gpii/node_modules/eventLog/src/eventLog.js, gpii/node_modules/eventLog/src/metrics.js
Some fixes I made for https://github.com/GPII/universal/pull/790 weren't very good, and caused a problem (https://github.com/GPII/windows/pull/270#issuecomment-625200006).
=> GPII-3853: Fixed metrics related test failure on gpii-windows

testData/solutions/win32.json5
See https://issues.gpii.net/browse/GPII-4506
=> GPII-4506: Fixed the "update" block of com.microsoft.windows.cursors

testData/defaultSettings/defaultSettings.win32.json5
See https://issues.gpii.net/browse/GPII-4507
=> GPII-4507: Updated content of defaultSettings.win32.json5

.github/workflows/ci.yml, gpii/node_modules/flowManager/src/MatchMaking.js
Here's one example of the CI pass https://github.com/javihernandez/universal/actions/runs/346103510
=> GPII-4526: Added workflow for github actions
