testData/preferences/li.json
testData/preferences/vladimir.json
testData/preferences/vladimir_smm.json

* Change magnification from 1.5 to 2 for gpii-default as Supernova can
only handle integer.
* Add max value to condition block. Required to work with the RBMM.

Fix magnification and condition issue

---

tests/platform/android/android-builtIn-testSpec.js
tests/platform/android/android-talkback-testSpec.js
tests/platform/linux/linux-builtIn-testSpec.js
tests/platform/linux/linux-orca-testSpec.js
tests/platform/windows/windows-builtIn-testSpec.js
tests/platform/windows/windows-jaws-testSpec.js
tests/platform/windows/windows-nvda-testSpec.js

so we're no longer dependent on the 'data' key when using the orca settingshandler, by replacing entries of 'data' with something similar to a solution ID

GPII-629: Changed the linux aceptance/integration tests to remove 'data' references

---

testData/solutions/win32.json
tests/platform/windows/windows-nvda-testSpec.js

The common term readingUnit should not transform to NVDA's autoSayAllOnPageLoad. Activating NVDA's autoSayAllOnPageLoad when the preference set contains the common term readingUnit might be a fallback inferred be a matchmaker, but the settings are not equivalent.

GPII-707: readingUnit != autoSayAllOnPageLoad

---

testData/preferences/c4a_p3_jose.json
testData/preferences/c4a_p3_katia.json
testData/preferences/c4a_p3_martha.json

In three NP sets, tracking or trackingTTS was not a proper enumeration.

GPII-1126: minor fix for tracking or trackingTTS

---

gpii/node_modules/flatMatchMaker/src/FlatMatchMaker.js

this is a shitty, horrific hack, but will allow the pilots to work. It should NOT, EVER, be merged into master

NOJIRA: Removed the usage of inferred common terms from the flat matchmaker

---

tests/platform/linux/linux-chrome-testSpec.js

GPII-989: Adding missing options block in linux-chrome-testSpec.js

---

.jshintignore
gpii/node_modules/gpii-oauth2/gpii-oauth2-authz-server/webTests/components/privacySettings/html/EditPrivacySettings-test.html
gpii/node_modules/gpii-oauth2/gpii-oauth2-authz-server/webTests/core/html/GPIIOauth2-test.html
gpii/node_modules/gpii-oauth2/gpii-oauth2-authz-server/webTests/lib/mockjax/js/jquery.mockjax.js
tests/all-tests.js
tests/platform/cloud/AcceptanceTests_chrome_oauth2.js

- Add jquery.mockjax.js, as needed by web tests for
gpii-oauth2-authz-server
- Add AcceptanceTests_oauth2_privacySettings.js to all-tests.js
- Set the truncateAt value for
gpii.tests.cloud.oauth2.disruptWithRevocation to 14 rather than 15.
The value of 15 left the 15th item, sendSecuredSettingsRequest, in
the list -- we want to truncate before this item and then append onto
the end of the list of actions.

GPII-17: Fix the OAuth2 tests

---

testData/preferences/acceptanceTests/olb_Alicia_cmn.json
testData/preferences/olb_Alicia_app.json
testData/preferences/olb_Alicia_cmn.json
testData/preferences/olb_preferences.md
testData/solutions/web.json
tests/platform/cloud/AcceptanceTests_olb.js
tests/platform/cloud/AcceptanceTests_olb.txt

This pull request contains the following:
* a new transformer for simplifiedUiEnabled,
* an acceptance test for the transformer for simplifiedUiEnabled,
* an NP set for the acceptance test,
* two NP sets to test simplifiedUiEnabled in the OLB: one using the common term (identical to the NP set for the acceptance test) and one using the application-specific term.

GPII-1282: add simplifiedUiEnabled to OLB

---

.gitignore
README.md
Vagrantfile
provisioning/playbook.yml
provisioning/requirements.yml
provisioning/vars.yml
tests/web/html/all-tests.html
tests/web/testem_qi.json

These changes add support for running automated browser tests (using [Testem](https://github.com/testem/testem)) and Node.js tests in a CI environment. The primary use case right now is the [GPII Jenkins server](https://ci.gpii.net/):
https://ci.gpii.net/job/universal-browser-tests/
https://ci.gpii.net/job/universal-browser-tests/tapResults.1.html

GPII-1507: Adds changes required for automated browser and node-based tests

---

Dockerfile
README.md
Vagrantfile

This PR moves to building the Docker image for universal using the Ansible nodejs role, the same approach used for bringing up Vagrant environments by #426 
Following merge the same approach will be reused for building the downstream containers at:
- https://github.com/gpii-ops/docker-flow-manager
- https://github.com/gpii-ops/docker-preferences-server
@avtar should eyeball this to make sure he's good with how I've refactored the Vagrant approach to let Docker and Vagrant share common variables where appropriate.

Update Docker build to use Ansible role

---

Dockerfile
provisioning/vars.yml

New versions of Node.js have been released to address multiple security issues.
https://nodejs.org/en/blog/vulnerability/february-2016-security-releases
As a result, the Docker images and the Ansible Node.js role need to be updated.

GPII-1564 - Update version of Node.js due to security issues

---

Dockerfile
provisioning/vars.yml

Changes:
https://nodejs.org/en/blog/release/v0.10.43
https://nodejs.org/en/blog/release/v0.10.44

GPII-1564 - Change node.js version required to 0.10.44

---

Dockerfile
provisioning/vars.yml

Since GPII/universal#425 and idi-ops/ansible-nodejs#27 were merged, we have adopted a new way of tracking Node.js versions. Instead of specific versions, we are favoring the choice between LTS (currently 4.x) or Current (6.x) versions. The most significant benefit for GPII/universal is that we don't have to keep changing versions every time there is a new one with security fixes. Container images will get rebuild automatically and it should be transparent in the case of the LTS branch (bug and security fixes and as few breaking changes as possible).
Right now GPII/universal won't work with 0.10.x anymore and that Docker image has already been erased, so it's important to merge this. The changes should be very low-impact and have been tested as a consequence of the work done in …

GPII-1318 - Comply with new LTS/Current split in supported Node.js versions

---

Vagrantfile

This pull request will hopefully save a few gigabytes on everyone's machine in the long run. It's a one-line fix.

GPII-1811: Updates Vagrant VM to Fedora 23.

---

gpii/node_modules/contextManager/test/data/standardMMInput.json
gpii/node_modules/matchMakerFramework/test/data/win32_full.json
testData/solutions/win32.json

Replaced calls to killProcessByName with closeProcessByName.
This depends on https://github.com/GPII/windows/pull/86

GPII-1540: AT persists after sleep/lock/UAC

---

gpii/node_modules/contextManager/test/data/standardMMInput.json
gpii/node_modules/matchMakerFramework/test/data/win32_full.json
testData/solutions/win32.json

Starting osk.exe via explorer, to ensure the native version is used.
This makes the On Screen Keyboard work on 64-bit Windows.

GPII-1757: Windows 10 can not start keyboard

---

testData/solutions/win32.json

Made the cursor also update after the settings have been restored.

GPII-2008: Cursor size remains large after running acceptance tests on Windows

---

testData/deviceReporter/installedSolutions.json
testData/solutions/solutionsDescription/com_ilunion_cloud4chrome.md
testData/solutions/win32.json

when using the dynamic device reporter

GPII-2109: Google chrome now never reports as being installed

---

Dockerfile
provisioning/vars.yml

It seems 'current' was being used and got committed to this repository as to make use of node.js 6.x (which wasn't released as a 'lts' release at the time).
This commit reverts that change since now node 6.x is a LTS release.
This should be a no-op.

GPII-2085 - Switch node.js version from 'current' to 'lts'

---

testData/solutions/win32.json

Updated the solutions registry to use "enableRegisteredAt" to start the built-in AT (osk and magnifier), as per https://github.com/GPII/windows/pull/98

GPII-2073: Persona Settings return on windows lock screen

---

vagrant-configs/provisioning/requirements.yml

To use the master branches of gpii-ops/ansible-preferences-server and gpii-ops/ansible-flow-manager since the pull requests on those repos for fixing GPII-1884 (https://github.com/gpii-ops/ansible-preferences-server/pull/2 and https://github.com/gpii-ops/ansible-flow-manager/pull/3) have been merged.

GPII-1884: Update provisioning/requirements.yml of the GPII production VM

---

gpii/node_modules/flowManager/src/FlowManager.js
gpii/node_modules/singleInstance/index.js
gpii/node_modules/singleInstance/package.json
gpii/node_modules/singleInstance/src/singleInstance.js
gpii/node_modules/singleInstance/test/SingleInstanceTests.js
tests/all-tests.js

Uses a "pid file", where the process's pid is put into a file. If the file exists, and it points to a running process, then it assumes GPII is already running.
Determining if the running process is really GPII will depend on (or partially duplicate) the process reporter, so for now there's a risk of another process re-using an old GPII's PID.

GPII-2235: Ensures there's only one instance of GPII

---

testData/deviceReporter/installedSolutions.json
testData/solutions/win32.json5

Just adds a registrySettingsHandler block to the com.microsoft.windows.highContrast block, which sets a registry value to the theme file. If highContrastEnabled is false, then nothing happens (but the registry value is still set)
Quick test: Log in as vladimir, and his white on black theme should be applied, rather than what was last used in Control Panel (default yellow on black).

GPII-252: Add support for highContrastTheme

---

gpii/configs/gpii.config.cloudBased.flowManager.production.json
gpii/configs/gpii.config.cloudBased.production.json
gpii/node_modules/flowManager/configs/gpii.flowManager.config.production.json

This is an initial change I would like to propose so Kasper's PR can be unlocked by pointing the Flow Manager at a different Preferences Server than the one hard coded into configuration files.
Please only merge this if this PR is accepted: https://github.com/fluid-project/kettle/pull/34 (KETTLE-62)

GPII-2470 - Add env var needed to specify where Preferences server is located

---

README.md
gpii/node_modules/flowManager/configs/gpii.flowManager.config.production.json
gpii/node_modules/preferencesServer/configs/gpii.preferencesServer.config.production.json

* GPII_PREFERENCES_LISTEN_PORT = TCP Port the Preferences Server should use
* GPII_PREFERENCES_DATASOURCE_URL = Location of the CouchDB database
* GPII_FLOWMANAGER_LISTEN_PORT = TCP Port the Flow Manager should use
* GPII_FLOWMANAGER_PREFERENCES_URL = Location of Preferences Server (Added in GPII-2470)
```
$ GPII_PREFERENCES_LISTEN_PORT=9999 \
GPII_PREFERENCES_DATASOURCE_URL=https://your-couchdb-server:5984/%userToken \
NODE_ENV=gpii.config.cloudBased.flowManager.production npm start
$ curl http://localhost:999/preferences/carla
```
```
$ GPII_FLOWMANAGER_LISTEN_PORT=10001 \
GPII_FLOWMANAGER_PREFERENCES_URL=https://preferences-staging.gpii.net/preferences/%userToken \
NODE_ENV=gpii.config.cloudBased.flowManager.production npm start
```

GPII-2411 - Add new env vars for Preferences Server and Flow Manager

---

gpii/node_modules/processReporter/src/processesBridge.js
gpii/node_modules/processReporter/test/web/js/ProcessesBridgeTests.js

@amb26, @stegru I found two bugs that partly explain the lag in windows in looking up targeted processes in the bridge.  They both involve a mistyped `"{arguments}.0"` in an `"args"` declaration, one in universal; the other in windows
This pull fixes the universal code.

GPII-442:  Fixed typo in argument list.

---

testData/deviceReporter/installedSolutions.json
testData/preferences/snapset_1a.json
testData/preferences/snapset_1b.json
testData/preferences/snapset_1c.json
testData/preferences/snapset_2a.json
testData/preferences/snapset_2b.json
testData/preferences/snapset_2c.json
testData/preferences/snapset_3.json
testData/preferences/snapset_4a.json
testData/preferences/snapset_4b.json
testData/preferences/snapset_4c.json
testData/preferences/snapset_4d.json

Also, updated snapsets with settings for UIO+ chrome extension.
You can read more about the motivation of this pull request here, https://issues.gpii.net/browse/GPII-2589
First, we are fixing the problem of windows not applying high contrast themes. With this pull request, the high contrast must be applied when logging in with any "snapset_2" users.
Second, now that the support for the UIO+ chrome extension is in master and the extension seems to be in a pretty good shape, we are also updating the snapsets to ensure that the settings for UIO+ work too. Although the UIO+ chrome extension is not going to be tested in this first round of pilots, we would like this to happen pretty soon, and we need QA to start testing the snapsets with the UIO+ chrome extension as soon as possible.
In order …

GPII-2589: Updated snapsets with required application specific settings

---

vagrant-configs/Vagrantfile

Adding code that is already in the main Vagrantfile to have the "split node_modules" solution so the node_modules outside the VM is separate from the one inside it.

GPII-2621 - Add split node_modules workaround

---

testData/preferences/snapset_1a.json
testData/preferences/snapset_1b.json
testData/preferences/snapset_1c.json
testData/preferences/snapset_2a.json
testData/preferences/snapset_2b.json
testData/preferences/snapset_2c.json
testData/preferences/snapset_3.json
testData/preferences/snapset_4a.json
testData/preferences/snapset_4b.json
testData/preferences/snapset_4c.json
testData/preferences/snapset_4d.json

Added user friendly names according to https://docs.google.com/document/d/1kaifumgrHacck2iyybESuMld_oDKlGtSAp0n0DqC-dk/edit

GPII-2644: Added user friendly names in APCP snapsets

---

gpii/node_modules/preferencesServer/test/preferencesServerTests.js
testData/deviceReporter/installedSolutions.json
testData/ontologies/flat.json5
testData/ontologies/mappings/ISO24751-flat.json5
testData/preferences/snapset_5.json
testData/solutions/win32.json5

Replacing https://github.com/GPII/universal/pull/568

GPII-2730: Added new snapset, solution registry entry and term for showcasing an 'OSRestart' setting

---

gpii/node_modules/settingsHandlers/src/NoSettingsHandler.js
testData/solutions/win32.json5

This is a temporary workaround for https://issues.gpii.net/browse/GPII-2106 until https://github.com/GPII/universal/pull/507 gets in.

GPII-2106: Workaround to close firefox when keying-out elaine

---

gpii/node_modules/lifecycleManager/src/LifecycleManager.js

https://issues.gpii.net/browse/GPII-2897

GPII-2897: Replaced 'fail' with 'reject' to actually reject a promise

---

testData/solutions/win32.json5

Fixes the "nvda doesn't close" bug discovered by Gregg, the actual problem being GPII thought NVDA wasn't running.
https://lists.gpii.net/pipermail/architecture/2018-July/004833.html

GPII-3208: Added ".exe" to the nvda process name to correctly detect if it's running.

---

gpii/node_modules/userListeners/src/listeners.js

Don't call proximityTrigger when removing the USB key and if not logged in.

GPII-3283: proximityTrigger / noUser hack

---

gpii/configs/gpii.config.untrusted.development.dynamicDR.json5

To start untrusted local flow manager with dynamic device reporter.

GPII-3284: Fixed the config used by QSS/PSP 

---

gpii/node_modules/lifecycleManager/src/LifecycleManager.js
tests/shared/PSPIntegrationTestDefs.js

@amb26, in [my previous pull request for GPII-3378](https://github.com/GPII/universal/pull/661), there was a bug that when sequentially applying changes for a new preference, only the first change would be successfully applied and the following would fail. 
This pull request contains a test to demonstrate the problem as well as a fix for it.
Please have a look. Thanks.

GPII-3378: Fix an issue with sequentially applying a new setting

---

testData/solutions/win32.json5

We need this to allow the QSS to effectively switch the OS language.

GPII-3414: Added liveness directive to com.microsoft.windows.language

---

tests/JournalIntegrationTests.js

By starting the normal login process after the restoration when "noUser" login completes.

GPII-3396: Fix the journal integration test failure on Windows

---

gpii/node_modules/gpii-user-errors/bundles/gpii-userErrors-messageBundle_en.json5

Adds a simple html `anchor` tags to User Error messages. These are handled properly in the `gpii.app` by the `gpii.app.errorDialog`.

GPII-3402: "Contact Technical Support" link to User Errors

---

testData/solutions/linux.json5
testData/solutions/win32.json5

https://issues.gpii.net/browse/GPII-3411

GPII-3411: Adding schemas for UIO+ solutions entries.

---

gpii/node_modules/settingsHandlers/src/NoSettingsHandler.js
gpii/node_modules/settingsHandlers/src/settingsHandlerUtilities.js
gpii/node_modules/settingsHandlers/test/NoSettingsHandlerTests.js
gpii/node_modules/settingsHandlers/test/SettingsHandlerUtilitiesTests.js
testData/solutions/win32.json5
tests/all-tests.js

After some investigation, I found we only need to fix [this line](https://github.com/GPII/universal/compare/master...cindyli:GPII-3422?expand=1#diff-cb7e20a6c5ff97630ea4518024a845b2R6424) for the "com.microsoft.windows.volumeControl" solution in the windows solution registry to get rid of the metrics "solution-failed" error.
However, since I've already improved "gpii.settingsHandler.noSettings" to return payloads, I also include it in this pull request. The benefit of this change is, a clearer logging message of the new volume value will be recorded in the flow manager log file when the new volume is applied.
@amb26, let me know if you think it's better NOT to merge the change for "gpii.settingsHandler.noSettings". Thanks.

GPII-3422: Fixed the metrics "solution-failed" error for "com.microsoft.windows.volumeControl" solution

---

testData/preferences/empty.json5

Suitable for testing functionalities such as:
- If the PSP is open and a user with no settings keys in, the PSP should be closed
- If a user with no settings has keyed in and the PSP is opened, a dedicated message about the missing settings will be shown.

NOJIRA: Adding an empty preference set for testing purposes

---

documentation/ResetComputer.md
gpii/node_modules/flowManager/src/DefaultSettingsLoader.js
gpii/node_modules/settingsHandlers/src/settingsHandlerUtilities.js
gpii/node_modules/settingsHandlers/test/web/js/SettingsHandlerUtilitiesTests.js
testData/snapshots/defaultSettings.win32.json5

This pull request does:
1. Fix the issue with resetting high contrast on system startup;
2. Move the location of defaultSettings.json5 from `testData/solutions` to `testData/snapshots`;
3. Created an initial snapshot for windows platform at `testData/snapshots/defaultSettings.win32.json5`. @javihernandez, please rename it to `testData/snapshots/defaultSettings.json5` at building windows installers. This file resets QSS supported settings: language, DPI, high contrast and read aloud.

GPII-3451, GPII-3452: Fix the issue with resetting high contrast on system startup

---

gpii/node_modules/eventLog/src/eventLog.js
gpii/node_modules/eventLog/src/metrics.js
gpii/node_modules/eventLog/test/EventLogTests.js

Instead of writing the metrics logs to disk (being readable by anyone), this fix sends the metrics directly to Filebeat via tcp.
A new `filebeat.msm` is available (see me, @javihernandez).
To test (without filebeat)
* Listen on port 51481, with something like [ncat](https://nmap.org/ncat/) (http://nmap.org/dist/ncat-portable-5.59BETA1.zip)
`nc -vlp 51481`

GPII-3449: Logging metrics via TCP

---

.gitattributes

I tested this on my fork, where I no longer need to click "Load diff" on PRs of .js files.
EDIT: link to example PR: https://github.com/mrtyler/universal/pull/1

"Load diff" button no more

---

gpii.js
package.json

Does nothing until https://github.com/gpii-ops/gpii-infra/pull/197 is merged, and for non-GCP [Google Cloud Platform] deployments (e.g. deployments to developer laptops).
I got here by following [these Trace docs](https://cloud.google.com/trace/docs/setup/nodejs).
Tested by hand with a locally-built and locally-run Docker container, and in my GCP dev environment.

GPII-3394: Add GCP Stackdriver Trace support

---

testData/solutions/win32.json5

Sometimes, the built-in apps names are shown in the wrong language from
the start menu. Setting HKCU\Control Panel\International\User Profile\Languages
and restarting the explorer fixes the issue.

GPII-3558: Added another registry key to set when switching language

---

gpii/node_modules/flowManager/src/FlowManager.js
tests/shared/PSPIntegrationTestDefs.js

The issue is that, when PSP client issues a setting change request after a reset action, PSP channel should only respond with the data for the new setting rather than responding with both settings applied before the reset action and the new setting.
https://issues.gpii.net/browse/GPII-3693

GPII-3693: Fix the issue with returning wrong PSPchannel response after a reset action

---

package.json

This pull updates universal to use the updates to gpii-couchdb-test-harness described in [GPII-3741](https://issues.gpii.net/browse/GPII-3741).

GPII-3741: Add support for "external" CouchDB instance.

---

testData/solutions/win32.json5

Fix required for the latest Windows build, 1810 (or whatever is it)

GPII-3811: Made the high-contrast theme work more.

---

index.js

When cleanly shutting down gpii, a null reference on `shadow` here: https://github.com/fluid-project/infusion/blob/23b4bc89d5bc03087dac78d9d192d3dbbeadeafa/src/framework/core/js/FluidIoC.js#L1068, when dealing with the grade for whatever config was used.
This causes the process to not fully shutdown and linger. This isn't usually noticeable as GPII generally only cleanly shuts down when signing out of Windows (so it just gets killed after some time), but now I'm making the installer shut it down.
Reversing the order in which the configs are disposed prevents this from happening.

 GPII-2338: Stopped GPII crashing on shutdown.

---

scripts/generateCredentials.js

See https://issues.gpii.net/browse/GPII-3714.
The script generates two files containing:
1. **secret.txt**: The file to be provided when building the "Secret Blower" installer. See https://github.com/GPII/morphic-credentials-installer/pull/1
2. **couchDBData.json**: The JSON-format documents that go into the production
database and ready to be inserted using an HTTP POST request

GPII-3714: Added a script that generates client credentials

---

gpii/node_modules/userListeners/src/listeners.js

We are including this workaround for GPII-3769 in the last installer to avoid the problems when keying-out until a proper fix is available.
Don't want this to be merged into master (unless we decide that we want to SHIP IT NOW) but I'm creating this PR just in case.

GPII-3769: Temporary workaround

---

scripts/deleteAndLoadSnapsets.sh

Some systems have a strict `/bin/sh`, which don't allow non-standard `==` expressions.
(mine links to `dash`)

NOJIRA: Made deleteAndLoadSnapsets.sh posix compliant

---

gpii/node_modules/flowManager/src/DefaultSettingsLoader.js
gpii/node_modules/flowManager/src/FlowManager.js
gpii/node_modules/flowManager/src/PSPChannel.js
gpii/node_modules/lifecycleManager/src/UserLogonStateChange.js
testData/solutions/linux.json5
tests/PSPIntegrationTests.js
tests/UntrustedPSPIntegrationTests.js
tests/configs/gpii.tests.acceptance.pspIntegration.config.json5
tests/configs/gpii.tests.acceptance.resetAtStart.config.json5
tests/configs/gpii.tests.acceptance.untrusted.pspIntegration.config.json
tests/configs/shared/gpii.tests.resetDefaultSettings.config.json5
tests/configs/shared/gpii.tests.userLogon.config.json5
tests/data/preferences/context1.json5
tests/shared/PSPIntegrationTestDefs.js
tests/shared/ResetDefaultSettingsTestDefs.js

This pull request also removes the inoperative implementation for [GPII-3828](https://issues.gpii.net/browse/GPII-3828) from the code. There has been [a new pull request for GPII-3828](https://github.com/GPII/universal/pull/820), which will be adjusted when this pull request is merged.

GPII-4250: Remove options modifications after the component construction from flowManager

---

gpii/node_modules/ontologyHandler/src/ontologyHandler.js
testData/preferences/jaws.json5

[The key-in failure](https://issues.gpii.net/browse/GPII-4225) is because in jaws.json5 the definition of the "/enabled" term is outside of the "preferences" block.

GPII-4225: Fix the issue with keying in "jaws"

---

Vagrantfile

Fedora 28 has reached end-of-life (EOL) on May 2019.
https://fedoraproject.org/wiki/End_of_life

FLUID-6486: vagrant: Use Fedora 31 box

---

README.md

fix issue - #864 
typo fix: added "an" before untrusted  in flow manager.

typo fix:README.md added "an" before untrusted .

---

gpii/node_modules/testing/src/Mocks.js
testData/solutions/win32.json5

This PR removes the references to `gpii.windows.rm` following the review of https://github.com/GPII/windows/pull/276 and according to [this comment](https://github.com/GPII/windows/pull/276#issuecomment-523447922).

GPII-4087: Removed gpii.windows.rm references from SR

---

gpii/node_modules/settingsHandlers/src/RemoteFileSettingsHandler.js
gpii/node_modules/settingsHandlers/test/RemoteFileSettingsHandlerTests.js
testData/solutions/win32.json5

Required by https://github.com/GPII/windows/pull/313, this allows the component used by the remoteFileSettingsHandler to be replaced.
Added bonus of creating a backup of original files which are about to be replaced.

GPII-4446: Modifying the existing ribbon, rather than replacing it.

---

testData/solutions/win32.json5

Removes the transform for the dpi, to make it work.

NOJIRA: Removed the DPI transform.

---

documentation/BrowserChannel.md
examples/browserChannelClient/browserChannelClient.js
examples/pspChannelClient/pspChannelClientApplyPrefs.js
examples/pspChannelClient/pspChannelClientReadPrefs.js
gpii/node_modules/flowManager/src/BrowserChannel.js
gpii/node_modules/flowManager/test/shared/BrowserChannelTestDefs.js
gpii/node_modules/settingsHandlers/src/WebSocketsSettingsHandler.js
gpii/node_modules/settingsHandlers/test/WebSocketsSettingsHandlerTests.js
testData/solutions/win32.json5

This pull request addresses two issues.  First, it solves the original problem where the PSPChannel read API could not read a UIO+ setting.  Secondly, it adds the ability for the BrowserChannel/WebSocketsSettingsHandler to write UIO+ settings, allowing [the UIO+ chrome extension for morphic](https://github.com/GPII/gpii-chrome-extension/pull/52) to send and receive messages from a running Morphic instance.
The `inverseCapabilitiesTransformations` block in the solutions registry for UIO+ was an empty disallowing any transformation from settings to preferences.  That meant any pspChannel request for a UIO+ preference was bound to fail.  All but one of the inverse transformations could be automatically generated by `gpii.getInverseRules()`, meaning that no inverse transformations would be …

GPII-4218:  PSPChannel read API cannot read UIO+ setting

---

tests/JournalIntegrationTests.js
tests/data/preferences/os_win.json5
tests/platform/windows/windows-builtIn-testSpec.js

Disabled volume setting to make windows builtIn acceptance tests to pass on github actions, see https://gpii.atlassian.net/browse/GPII-4518

GPII-4517: Disabled Volume setting in integration/acceptance tests
